name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update packages
        run: sudo apt-get update

      - name: Install Yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update && sudo apt-get install -y yarn

      - name: Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the project
        run: |
          yarn --silent
          yarn build
        env:
          VITE_APP_ENV: test
          VITE_APP_OPEN_PROXY: false
          VITE_APP_BASE_URL: https://test-admin-api.new.vincentcapital.co.nz/api
          VITE_APP_TOKEN_PREFIX: vc-online-user-token

      - name: Deploy to AWS S3
        run: |
          aws s3 rm s3://test-vco.new.vincentcapital.co.nz --recursive --quiet
          aws s3 cp build/ s3://test-vco.new.vincentcapital.co.nz --recursive --quiet
          aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTING_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: ap-southeast-2